services:
  gateway:
    image: ghcr.io/rutkowski-tomasz/api-gateway:v0.0.1
    container_name: gateway
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - VERSION=v0.0.1
      - ENVIRONMENT=prod
    ports:
      - 80:80
      - 443:443
    networks:
      - proxynetwork
    
  api1:
    container_name: api1
    image: ghcr.io/rutkowski-tomasz/sample-api:alpha002
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - VERSION=alpha002-api1
      - ENVIRONMENT=prod
      - COGNITO_USERPOOL_ID=eu-central-1_0nZs7Q8yU
      - COGNITO_CLIENT_ID=3sg1ii35h1pg3j268mr3smcnro
    networks:
      - proxynetwork

  api2:
    container_name: api2
    image: ghcr.io/rutkowski-tomasz/sample-api:alpha002
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - VERSION=alpha002-api2
      - ENVIRONMENT=prod
      - COGNITO_USERPOOL_ID=eu-central-1_0nZs7Q8yU
      - COGNITO_CLIENT_ID=3sg1ii35h1pg3j268mr3smcnro
    networks:
      - proxynetwork
  
networks:
  proxynetwork:
    name: proxynetwork
    driver: bridge
