services:
  gateway:
    image: ghcr.io/rutkowski-tomasz/api-gateway:latest
    container_name: gateway
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Gateway__Compression__Level=Fastest
      - Gateway__Services__0__Name=api1
      - Gateway__Services__1__Name=api2
      - Gateway__Services__1__Prefix=public
      - Gateway__Services__1__RateLimiting__PermitLimit=10
      - Gateway__Services__1__RateLimiting__WindowSeconds=60
      - Gateway__Services__1__Cors__Origins__0=http://localhost:3000
      - Gateway__Services__1__Cors__Origins__1=http://localhost:5000
    ports:
      - 80:80
      - 443:443
    networks:
      - proxynetwork
    
  api1:
    container_name: api1
    image: wiremock/wiremock:latest
    environment:
      - wiremock.service_name=api1
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--port", "80", "--global-response-templating", "--disable-gzip", "--disable-banner"]
    networks:
      - proxynetwork

  api2:
    container_name: api2
    image: wiremock/wiremock:latest
    environment:
      - wiremock.service_name=api2
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--port", "80", "--global-response-templating", "--disable-gzip", "--disable-banner"]
    networks:
      - proxynetwork

networks:
  proxynetwork:
    name: proxynetwork
    driver: bridge
