version: '3.8'

services:
  gateway:
    image: ghcr.io/rutkowski-tomasz/api-gateway:latest
    container_name: gateway
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 80:80
      - 443:443
    networks:
      - proxynetwork
    
  api1:
    container_name: api1
    image: ghcr.io/rutkowski-tomasz/sample-api:v0.1.3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VERSION=v0.1.3-api1
      - ENVIRONMENT=prod
      - COGNITO_USERPOOL_ID=eu-central-1_0nZs7Q8yU
      - COGNITO_CLIENT_ID=3sg1ii35h1pg3j268mr3smcnro
    networks:
      - proxynetwork

  api2:
    container_name: api2
    image: ghcr.io/rutkowski-tomasz/sample-api:v0.1.3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VERSION=v0.1.3-api2
      - ENVIRONMENT=prod
      - COGNITO_USERPOOL_ID=eu-central-1_0nZs7Q8yU
      - COGNITO_CLIENT_ID=3sg1ii35h1pg3j268mr3smcnro
    networks:
      - proxynetwork
  
networks:
  proxynetwork:
    name: proxynetwork
    driver: bridge
