services:
  gateway:
    image: ghcr.io/rutkowski-tomasz/api-gateway:latest
    container_name: gateway
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Gateway__Compression__Level=Fastest
      - Gateway__Services__0__Name=api1
      - Gateway__Services__1__Name=api2
    ports:
      - 80:80
      - 443:443
    networks:
      - proxynetwork
    
  api1:
    container_name: api1
    image: wiremock/wiremock:latest
    environment:
      - wiremock.service_name=api1
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--port", "80", "--verbose", "--global-response-templating", "--disable-gzip"]
    networks:
      - proxynetwork

  api2:
    container_name: api2
    image: wiremock/wiremock:latest
    environment:
      - wiremock.service_name=api2
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--port", "80", "--verbose", "--global-response-templating", "--disable-gzip"]
    networks:
      - proxynetwork

networks:
  proxynetwork:
    name: proxynetwork
    driver: bridge
