@BaseUrl = http://localhost:80

###
GET {{BaseUrl}}/health

###
GET {{BaseUrl}}/api1/echo
Accept-Encoding:
X-Custom-Header: override-custom-header

###
GET {{BaseUrl}}/api2/echo
X-Custom-Header: override-custom-header
Origin: http://localhost:5000
